import { INDUSTRY_KB_ID } from './constants';

/** React Flow 节点样式 */
const S = {
  start: { background: '#00d4ff20', border: '1px solid #00d4ff', borderRadius: 8, color: '#fff', padding: 10, minWidth: 80 },
  end: { background: '#00ff8820', border: '1px solid #00ff88', borderRadius: 8, color: '#fff', padding: 10, minWidth: 80 },
  rag: { background: '#f59e0b20', border: '1px solid #f59e0b', borderRadius: 8, color: '#fff', padding: 10, minWidth: 120 },
  agent: { background: '#7c3aed20', border: '1px solid #7c3aed', borderRadius: 8, color: '#fff', padding: 10, minWidth: 110 },
  parallel: { background: '#06b6d420', border: '2px solid #06b6d4', borderRadius: 8, color: '#fff', padding: 10, minWidth: 100 },
  merge: { background: '#06b6d420', border: '2px dashed #06b6d4', borderRadius: 8, color: '#fff', padding: 10, minWidth: 100 },
  condition: { background: '#ef444420', border: '1px solid #ef4444', borderRadius: 8, color: '#fff', padding: 10, minWidth: 100 },
  tool: { background: '#64748b20', border: '1px solid #64748b', borderRadius: 8, color: '#fff', padding: 10, minWidth: 90 },
  http: { background: '#3b82f620', border: '1px solid #3b82f6', borderRadius: 8, color: '#fff', padding: 10, minWidth: 90 },
};

export interface SeedWorkflowDef {
  id: string;
  name: string;
  description: string;
  status: 'ACTIVE' | 'DRAFT';
  nodes: Array<Record<string, unknown>>;
  edges: Array<Record<string, unknown>>;
}

/** 4 条工业级演示工作流 — 含并行网关、条件分支、多 Agent 协同 */
export const DEMO_WORKFLOWS: SeedWorkflowDef[] = [
  {
    id: 'demo-workflow-001',
    name: '无人机协同生产计划',
    description: '订单接入 → 双路并行(MPS+MRP) → 布局/排程 → 仿真验证 → 协同决策',
    status: 'ACTIVE',
    nodes: [
      { id: 'start', type: 'start', position: { x: 0, y: 280 }, data: { label: '订单接入' }, style: S.start },
      { id: 'rag-1', type: 'rag', position: { x: 160, y: 280 }, data: { label: 'RAG·MPS规范', knowledgeBaseId: INDUSTRY_KB_ID, query: '无人机 MPS 主生产计划' }, style: S.rag },
      { id: 'fork-1', type: 'parallel', position: { x: 360, y: 280 }, data: { label: '并行·计划/物料' }, style: S.parallel },
      { id: 'agent-planner', type: 'agent', position: { x: 540, y: 120 }, data: { label: 'AI 计划员', agentId: 'template-planner' }, style: S.agent },
      { id: 'agent-analyst', type: 'agent', position: { x: 540, y: 440 }, data: { label: 'AI 数据员', agentId: 'template-data_analyst' }, style: S.agent },
      { id: 'merge-1', type: 'merge', position: { x: 720, y: 280 }, data: { label: '合并·计划方案' }, style: S.merge },
      { id: 'rag-2', type: 'rag', position: { x: 900, y: 280 }, data: { label: 'RAG·BOM/MRP', knowledgeBaseId: INDUSTRY_KB_ID, query: '多级 BOM MRP 物料需求' }, style: S.rag },
      { id: 'fork-2', type: 'parallel', position: { x: 1080, y: 280 }, data: { label: '并行·布局/排程' }, style: S.parallel },
      { id: 'agent-designer', type: 'agent', position: { x: 1260, y: 120 }, data: { label: 'AI 设计师', agentId: 'template-designer' }, style: S.agent },
      { id: 'agent-scheduler', type: 'agent', position: { x: 1260, y: 440 }, data: { label: 'AI 排程员', agentId: 'template-scheduler' }, style: S.agent },
      { id: 'merge-2', type: 'merge', position: { x: 1440, y: 280 }, data: { label: '合并·排产方案' }, style: S.merge },
      { id: 'cond-1', type: 'condition', position: { x: 1620, y: 280 }, data: { label: '产能可行?', condition: 'approved' }, style: S.condition },
      { id: 'agent-simulator', type: 'agent', position: { x: 1800, y: 120 }, data: { label: 'AI 仿真员', agentId: 'template-simulator' }, style: S.agent },
      { id: 'agent-dispatcher', type: 'agent', position: { x: 1800, y: 440 }, data: { label: 'AI 调度员', agentId: 'template-dispatcher' }, style: S.agent },
      { id: 'merge-3', type: 'merge', position: { x: 1980, y: 280 }, data: { label: '合并·验证结果' }, style: S.merge },
      { id: 'agent-decision', type: 'agent', position: { x: 2160, y: 280 }, data: { label: '协同决策员', agentId: 'template-decision' }, style: S.agent },
      { id: 'end', type: 'end', position: { x: 2340, y: 280 }, data: { label: '计划发布' }, style: S.end },
    ],
    edges: [
      { id: 'e01', source: 'start', target: 'rag-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e02', source: 'rag-1', target: 'fork-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e03', source: 'fork-1', target: 'agent-planner', label: 'MPS', style: { stroke: '#06b6d4' } },
      { id: 'e04', source: 'fork-1', target: 'agent-analyst', label: 'MRP', style: { stroke: '#06b6d4' } },
      { id: 'e05', source: 'agent-planner', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'e06', source: 'agent-analyst', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'e07', source: 'merge-1', target: 'rag-2', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e08', source: 'rag-2', target: 'fork-2', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e09', source: 'fork-2', target: 'agent-designer', label: '布局', style: { stroke: '#06b6d4' } },
      { id: 'e10', source: 'fork-2', target: 'agent-scheduler', label: '排程', style: { stroke: '#06b6d4' } },
      { id: 'e11', source: 'agent-designer', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'e12', source: 'agent-scheduler', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'e13', source: 'merge-2', target: 'cond-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e14', source: 'cond-1', target: 'agent-simulator', label: '通过', style: { stroke: '#00ff88' } },
      { id: 'e15', source: 'cond-1', target: 'agent-dispatcher', label: '否', style: { stroke: '#ef4444' } },
      { id: 'e16', source: 'agent-simulator', target: 'merge-3', style: { stroke: '#7c3aed' } },
      { id: 'e17', source: 'agent-dispatcher', target: 'merge-3', style: { stroke: '#7c3aed' } },
      { id: 'e18', source: 'merge-3', target: 'agent-decision', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'e19', source: 'agent-decision', target: 'end', animated: true, style: { stroke: '#00ff88' } },
    ],
  },
  {
    id: 'demo-workflow-002',
    name: 'SMT 智能排程与换线优化',
    description: 'SPI/AOI 知识检索 → 并行排程+质量 → SMED工具 → 急单分支 → 甘特图输出',
    status: 'ACTIVE',
    nodes: [
      { id: 'start', type: 'start', position: { x: 0, y: 300 }, data: { label: '工单下达' }, style: S.start },
      { id: 'rag-1', type: 'rag', position: { x: 150, y: 300 }, data: { label: 'RAG·排程手册', knowledgeBaseId: INDUSTRY_KB_ID, query: 'SMT 贴片产线智能排程' }, style: S.rag },
      { id: 'http-1', type: 'http', position: { x: 320, y: 300 }, data: { label: 'MES 产线状态', url: 'http://127.0.0.1:3001/api/health' }, style: S.http },
      { id: 'fork-1', type: 'parallel', position: { x: 500, y: 300 }, data: { label: '并行·排程/质检' }, style: S.parallel },
      { id: 'agent-scheduler', type: 'agent', position: { x: 680, y: 130 }, data: { label: 'AI 排程员', agentId: 'template-scheduler' }, style: S.agent },
      { id: 'agent-quality', type: 'agent', position: { x: 680, y: 470 }, data: { label: 'AI 质量员', agentId: 'template-quality' }, style: S.agent },
      { id: 'merge-1', type: 'merge', position: { x: 860, y: 300 }, data: { label: '合并·方案' }, style: S.merge },
      { id: 'tool-smed', type: 'tool', position: { x: 1040, y: 300 }, data: { label: 'SMED 换线工具', toolName: 'smed_optimizer' }, style: S.tool },
      { id: 'cond-rush', type: 'condition', position: { x: 1220, y: 300 }, data: { label: '急单插入?', condition: 'approved' }, style: S.condition },
      { id: 'agent-dispatcher', type: 'agent', position: { x: 1400, y: 130 }, data: { label: 'AI 调度员', agentId: 'template-dispatcher' }, style: S.agent },
      { id: 'agent-planner', type: 'agent', position: { x: 1400, y: 470 }, data: { label: 'AI 计划员', agentId: 'template-planner' }, style: S.agent },
      { id: 'merge-2', type: 'merge', position: { x: 1580, y: 300 }, data: { label: '合并·最终排程' }, style: S.merge },
      { id: 'agent-simulator', type: 'agent', position: { x: 1760, y: 300 }, data: { label: 'AI 仿真员', agentId: 'template-simulator' }, style: S.agent },
      { id: 'agent-decision', type: 'agent', position: { x: 1940, y: 300 }, data: { label: '协同决策员', agentId: 'template-decision' }, style: S.agent },
      { id: 'end', type: 'end', position: { x: 2120, y: 300 }, data: { label: '甘特图发布' }, style: S.end },
    ],
    edges: [
      { id: 's1', source: 'start', target: 'rag-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's2', source: 'rag-1', target: 'http-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's3', source: 'http-1', target: 'fork-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's4', source: 'fork-1', target: 'agent-scheduler', label: '排程', style: { stroke: '#06b6d4' } },
      { id: 's5', source: 'fork-1', target: 'agent-quality', label: 'SPC', style: { stroke: '#06b6d4' } },
      { id: 's6', source: 'agent-scheduler', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 's7', source: 'agent-quality', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 's8', source: 'merge-1', target: 'tool-smed', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's9', source: 'tool-smed', target: 'cond-rush', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's10', source: 'cond-rush', target: 'agent-dispatcher', label: '是', style: { stroke: '#ef4444' } },
      { id: 's11', source: 'cond-rush', target: 'agent-planner', label: '否', style: { stroke: '#00ff88' } },
      { id: 's12', source: 'agent-dispatcher', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 's13', source: 'agent-planner', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 's14', source: 'merge-2', target: 'agent-simulator', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's15', source: 'agent-simulator', target: 'agent-decision', animated: true, style: { stroke: '#00d4ff' } },
      { id: 's16', source: 'agent-decision', target: 'end', animated: true, style: { stroke: '#00ff88' } },
    ],
  },
  {
    id: 'demo-workflow-003',
    name: '新能源质量追溯闭环',
    description: 'VIN追溯RAG → 并行质量+数据 → SPC分析 → 仿真验证 → 决策闭环',
    status: 'ACTIVE',
    nodes: [
      { id: 'start', type: 'start', position: { x: 0, y: 320 }, data: { label: 'VIN 接入' }, style: S.start },
      { id: 'rag-1', type: 'rag', position: { x: 160, y: 320 }, data: { label: 'RAG·追溯规范', knowledgeBaseId: INDUSTRY_KB_ID, query: '整车 VIN 追溯 关键件绑定' }, style: S.rag },
      { id: 'fork-1', type: 'parallel', position: { x: 360, y: 320 }, data: { label: '并行·质量/数据' }, style: S.parallel },
      { id: 'agent-quality', type: 'agent', position: { x: 540, y: 140 }, data: { label: 'AI 质量员', agentId: 'template-quality' }, style: S.agent },
      { id: 'agent-analyst', type: 'agent', position: { x: 540, y: 500 }, data: { label: 'AI 数据员', agentId: 'template-data_analyst' }, style: S.agent },
      { id: 'merge-1', type: 'merge', position: { x: 720, y: 320 }, data: { label: '合并·追溯链' }, style: S.merge },
      { id: 'rag-2', type: 'rag', position: { x: 900, y: 320 }, data: { label: 'RAG·SPC标准', knowledgeBaseId: INDUSTRY_KB_ID, query: '冲压件 SPC 控制图' }, style: S.rag },
      { id: 'tool-spc', type: 'tool', position: { x: 1080, y: 320 }, data: { label: 'SPC 控制图', toolName: 'spc_xbar_r' }, style: S.tool },
      { id: 'cond-1', type: 'condition', position: { x: 1260, y: 320 }, data: { label: 'SPC 受控?', condition: 'approved' }, style: S.condition },
      { id: 'agent-simulator', type: 'agent', position: { x: 1440, y: 160 }, data: { label: 'AI 仿真员', agentId: 'template-simulator' }, style: S.agent },
      { id: 'agent-dispatcher', type: 'agent', position: { x: 1440, y: 480 }, data: { label: 'AI 调度员', agentId: 'template-dispatcher' }, style: S.agent },
      { id: 'merge-2', type: 'merge', position: { x: 1620, y: 320 }, data: { label: '合并·处置' }, style: S.merge },
      { id: 'fork-2', type: 'parallel', position: { x: 1800, y: 320 }, data: { label: '并行·优化/决策' }, style: S.parallel },
      { id: 'agent-designer', type: 'agent', position: { x: 1980, y: 180 }, data: { label: 'AI 设计师', agentId: 'template-designer' }, style: S.agent },
      { id: 'agent-decision', type: 'agent', position: { x: 1980, y: 460 }, data: { label: '协同决策员', agentId: 'template-decision' }, style: S.agent },
      { id: 'merge-3', type: 'merge', position: { x: 2160, y: 320 }, data: { label: '合并·闭环' }, style: S.merge },
      { id: 'end', type: 'end', position: { x: 2340, y: 320 }, data: { label: '追溯归档' }, style: S.end },
    ],
    edges: [
      { id: 'v1', source: 'start', target: 'rag-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v2', source: 'rag-1', target: 'fork-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v3', source: 'fork-1', target: 'agent-quality', label: '追溯', style: { stroke: '#06b6d4' } },
      { id: 'v4', source: 'fork-1', target: 'agent-analyst', label: '数据', style: { stroke: '#06b6d4' } },
      { id: 'v5', source: 'agent-quality', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'v6', source: 'agent-analyst', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'v7', source: 'merge-1', target: 'rag-2', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v8', source: 'rag-2', target: 'tool-spc', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v9', source: 'tool-spc', target: 'cond-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v10', source: 'cond-1', target: 'agent-simulator', label: '受控', style: { stroke: '#00ff88' } },
      { id: 'v11', source: 'cond-1', target: 'agent-dispatcher', label: '失控', style: { stroke: '#ef4444' } },
      { id: 'v12', source: 'agent-simulator', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'v13', source: 'agent-dispatcher', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'v14', source: 'merge-2', target: 'fork-2', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'v15', source: 'fork-2', target: 'agent-designer', label: '布局', style: { stroke: '#06b6d4' } },
      { id: 'v16', source: 'fork-2', target: 'agent-decision', label: '决策', style: { stroke: '#06b6d4' } },
      { id: 'v17', source: 'agent-designer', target: 'merge-3', style: { stroke: '#7c3aed' } },
      { id: 'v18', source: 'agent-decision', target: 'merge-3', style: { stroke: '#7c3aed' } },
      { id: 'v19', source: 'merge-3', target: 'end', animated: true, style: { stroke: '#00ff88' } },
    ],
  },
  {
    id: 'demo-workflow-004',
    name: '多 Agent 全局协同决策',
    description: '合同网任务发布 → 三路竞标(计划/排程/质量) → 调度分配 → 仿真 → 全局决策',
    status: 'ACTIVE',
    nodes: [
      { id: 'start', type: 'start', position: { x: 0, y: 350 }, data: { label: '任务发布' }, style: S.start },
      { id: 'rag-1', type: 'rag', position: { x: 140, y: 350 }, data: { label: 'RAG·CNP协议', knowledgeBaseId: INDUSTRY_KB_ID, query: 'Contract Net 合同网协议' }, style: S.rag },
      { id: 'agent-dispatcher', type: 'agent', position: { x: 320, y: 350 }, data: { label: 'AI 调度员', agentId: 'template-dispatcher' }, style: S.agent },
      { id: 'fork-1', type: 'parallel', position: { x: 520, y: 350 }, data: { label: '并行·Agent竞标' }, style: S.parallel },
      { id: 'agent-planner', type: 'agent', position: { x: 700, y: 100 }, data: { label: 'AI 计划员', agentId: 'template-planner' }, style: S.agent },
      { id: 'agent-scheduler', type: 'agent', position: { x: 700, y: 350 }, data: { label: 'AI 排程员', agentId: 'template-scheduler' }, style: S.agent },
      { id: 'agent-quality', type: 'agent', position: { x: 700, y: 600 }, data: { label: 'AI 质量员', agentId: 'template-quality' }, style: S.agent },
      { id: 'merge-1', type: 'merge', position: { x: 900, y: 350 }, data: { label: '合并·竞标结果' }, style: S.merge },
      { id: 'cond-1', type: 'condition', position: { x: 1080, y: 350 }, data: { label: '资源冲突?', condition: 'approved' }, style: S.condition },
      { id: 'agent-analyst', type: 'agent', position: { x: 1260, y: 180 }, data: { label: 'AI 数据员', agentId: 'template-data_analyst' }, style: S.agent },
      { id: 'agent-designer', type: 'agent', position: { x: 1260, y: 520 }, data: { label: 'AI 设计师', agentId: 'template-designer' }, style: S.agent },
      { id: 'merge-2', type: 'merge', position: { x: 1440, y: 350 }, data: { label: '合并·消解方案' }, style: S.merge },
      { id: 'agent-simulator', type: 'agent', position: { x: 1620, y: 350 }, data: { label: 'AI 仿真员', agentId: 'template-simulator' }, style: S.agent },
      { id: 'agent-decision', type: 'agent', position: { x: 1800, y: 350 }, data: { label: '协同决策员', agentId: 'template-decision' }, style: S.agent },
      { id: 'tool-report', type: 'tool', position: { x: 1980, y: 350 }, data: { label: '决策报告', toolName: 'decision_report' }, style: S.tool },
      { id: 'end', type: 'end', position: { x: 2160, y: 350 }, data: { label: '任务下发' }, style: S.end },
    ],
    edges: [
      { id: 'm1', source: 'start', target: 'rag-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm2', source: 'rag-1', target: 'agent-dispatcher', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm3', source: 'agent-dispatcher', target: 'fork-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm4', source: 'fork-1', target: 'agent-planner', label: '计划', style: { stroke: '#06b6d4' } },
      { id: 'm5', source: 'fork-1', target: 'agent-scheduler', label: '排程', style: { stroke: '#06b6d4' } },
      { id: 'm6', source: 'fork-1', target: 'agent-quality', label: '质量', style: { stroke: '#06b6d4' } },
      { id: 'm7', source: 'agent-planner', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'm8', source: 'agent-scheduler', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'm9', source: 'agent-quality', target: 'merge-1', style: { stroke: '#7c3aed' } },
      { id: 'm10', source: 'merge-1', target: 'cond-1', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm11', source: 'cond-1', target: 'agent-analyst', label: '有冲突', style: { stroke: '#ef4444' } },
      { id: 'm12', source: 'cond-1', target: 'agent-designer', label: '无冲突', style: { stroke: '#00ff88' } },
      { id: 'm13', source: 'agent-analyst', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'm14', source: 'agent-designer', target: 'merge-2', style: { stroke: '#7c3aed' } },
      { id: 'm15', source: 'merge-2', target: 'agent-simulator', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm16', source: 'agent-simulator', target: 'agent-decision', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm17', source: 'agent-decision', target: 'tool-report', animated: true, style: { stroke: '#00d4ff' } },
      { id: 'm18', source: 'tool-report', target: 'end', animated: true, style: { stroke: '#00ff88' } },
    ],
  },
];
